### ISSUE TITLE
c2，重命名组件的 save 方法

### ISSUE THREAD

**Issue by LeiQiao** [chinapnr/JR#13]
重命名组件的 save 方法，save 表示的意义有歧义，改为 compile 或其它名称

**Comment by wingfish** [comment]
我建议这里不一定要写出所有的 code，不过大致修改哪个文件，可以标明一下。
code review 的时候大家交叉 review。

**Comment by LeiQiao** [comment]
save 之前的意思是把用 dsl 创建的组件保存到一个文件中，生成一个页面，比如：
```python
table = SimpleTable()
table.save('test_table.html')
```
