### ISSUE TITLE
自定义创建/编译项目的位置

### ISSUE THREAD

**Issue by LeiQiao** [chinapnr/JR#14]
目前创建和编译项目的位置在 projects 文件夹中，对 jr 或其它项目的项目管理方式有冲突，在 jr 的创建/编译脚本中增加项目位置的选项指定项目的位置

**Comment by wingfish** [comment]
Projects 文件夹有点没有看明白，后面的意思就是 jr 命令行创建脚本时候可以输入项目创建在哪个目录下？
然后建议之后创建目录树这个功能可以由 fishbase 提供标准函数完成，项目文件名结构可以写在配置文件里，作为 fishbase 默认支持也可以。这个细节可以在 fishbase 相关特性中讨论。来简化这里的逻辑。

**Comment by wingfish** [comment]
类似创建项目这样比较常见的命令，可以考虑 jr -c 以及 jr --create 来支持，命令行参数需要一个统一约定。

jr 命令创建的项目相关的名称、位置、类型等如何给 c1 c2 都用到？

然后目前 jr 命令行是属于 cmd 这个部分，是否？

以上只是看到建议，如果需要修改，另外开 issue 了。

**Comment by iTaa** [comment]
1. 目前命令行是属于cmd的部分。
2. 如果使用 `jr -c / jr --create` `-c/--create` 属于 jr的`OPTIONS`，这种方式在命令复杂的时候`OPTIONS`会很多，用起来不是很方便，扩展也不够好。
3. jr的命令行采用了group方式将命令行按照划分开，创建：`jr create [OPTIONS] [PROJECT_NAME]`, 编译：`jr compile [OPTIONS] [PROJECT_NAME]`，类似setup.py的命令行，`setup.py build ....` `setup.py install ....`，如下是`jr --help` 得到的帮助文档：
```
Usage: jr [OPTIONS] COMMAND [ARGS]...

  jarvis rules 启动命令行管理工具

Options:
  --help  Show this message and exit.

Commands:
  compile  编译 JR 项目
  create   新建 JR 项目
```
`jr create --help`：
```
Usage: jr create [OPTIONS] [PROJECT_NAME]

  新建 JR 项目

Options:
  -q, --quite
  --help       Show this message and exit.
```
 `jr compile --help`：
```
Usage: jr compile [OPTIONS] [PROJECT_NAME]

  编译 JR 项目

Options:
  --release
  -q, --quite
  --help       Show this message and exit.
```

**Comment by wingfish** [comment]
1 用命令行中的command 没问题。不过最好意义是一样的，就是最主要的操作用几个命令，然后跟着相关参数。
2 看了这个说明，有新的问题， 一般是 -H --help 对应，或者 -h --help
3 然后 create 和 compile 中的 -q 和 --quite 是什么命令？是 quiet？
4 --release 是什么？

**Comment by LeiQiao** [comment]
当前 bug 已经修复，新问题开 #41
