### ISSUE TITLE
整合成Python Package形式

### ISSUE THREAD

**Issue by iTaa** [chinapnr/JR#21]
## 整合成Python Package形式
因zion中要import jr，为了便于使用以及后期维护方便，将jr整合成Python Package形式
1. 新增setup.py并编写配置参数
2. 将项目中`jr.py`改为 `_cmd.py`, 提供`console_scripts`入口函数`main`
3. 简化命令行参数，将`build_project`和`create_project`，改为`build`和`create`

## 安装说明
```
pip install git+https://github.com/chinapnr/JR.git@v0.0.1_develop
```

**Comment by CharlesHuang1985** [comment]
_cmd.py 的命名有什么讲究么？

**Comment by iTaa** [comment]
下划线开头为私有模块，不会被外部调用，`_cmd.py`这个只是命令行相关的功能，不会给外部使用
