### ISSUE TITLE
命令行生成Project默认目录调整

### ISSUE THREAD

**Issue by iTaa** [chinapnr/JR#23]
## 命令行生成Project默认目录调整
将jr项目整合成Python Package后，jr会在`pip install`的时候默认安装到`site-package`中，之前生成项目的默认目录是`project.py`所在的路径（安装后`project.py`在`site-package`下，也就意味着新建的项目会被创建到`site-package`下），需要更改，暂更改为执行`jr`命令的当前目录，既：`(.)`

**Comment by CharlesHuang1985** [comment]
JR 的 install 位置感觉不是最大问题，应该是 create 出来的 project 的位置可以由使用方指定
