### ISSUE TITLE
cmd， jr 命令行优化

### ISSUE THREAD

**Issue by iTaa** [chinapnr/JR#41]
## jr 命令行优化
1. 完善命令行帮助文档
2. --quite 修改为--quiet

**Comment by wingfish** [comment]
release 选项如果是是否输出 debug 信息的话，为什么不就是 --debug 呢？

**Comment by iTaa** [comment]
release 参数默认是 false，也就是默认开启的是debug模式，使用`jr compile --release [PROJECT_NAME]` 就可以用来编译release版本，如果参数是`--debug`的话，编译release版本的命令为`jr compile --debug=false [PROJECT_NAME]`, 前者略简洁一些

**Comment by wingfish** [comment]
我总觉得这个设计有点不够优雅，jr compile [project_name] 就可以理解为编译正式版本，加一个 debug 表示在 debug 模式，没有就是默认 debug=false，放一个 release 有点多余。你们在考虑一下。
