### ISSUE TITLE
添加travis-ci自动化构建配置

### ISSUE THREAD

**Issue by iTaa** [chinapnr/JR#7]
## 添加travis-ci自动化构建配置
新增文件`.travis.yml`, travis-ci自动化构建配置文件，文件内容可参考`fishbase`的写法https://github.com/chinapnr/fishbase/blob/master/.travis.yml
详细说明见travis-ci官网https://docs.travis-ci.com/user/languages/python/

**Comment by wingfish** [comment]
我看了 requerments 里面

atomicwrites==1.1.5
attrs==18.1.0
certifi==2018.4.16
more-itertools==4.2.0
pluggy==0.6.0
py==1.5.3
pytest==3.6.2
six==1.11.0

1 pytest 我记得可以不放在配置文件中，ti 这里默认安装的吧
2 其他包都是做什么用处的? 我们对 python 的第三方包和版本有管理的

**Comment by iTaa** [comment]
atomicwrites, attrs  py, six, more-itertools,  这些都是pytest的依赖包，ti这里默认安装pytest, 可以不用写到requerments
